### ISSUE TITLE
Feature request: Add support for doc strings

### ISSUE THREAD

**Issue by CarlKCarlK** [K-Vinayak/gen_ops#1]
Thanks for the great package! It was just what I needed. It would be great if it supported doc strings. I think just one docstring per "for" that would be repeated among all the combinations generated by gen_ops_ex.

Yours,
Carl
https://github.com/CarlKCarlK & https://medium.com/@carlmkadie

**Comment by K-Vinayak** [comment]
Hello Carl,

Sorry for the long delay in reply. I got busy with other things. 

I believe it's possible to implement this feature. I'll look into this soon. 

Regards,
K Vinayak

**Comment by CarlKCarlK** [comment]
Thanks! BTW: I recommend gen_ops in this article that came out this week:
https://medium.com/towards-data-science/nine-rules-for-creating-fast-safe-and-compatible-data-structures-in-rust-part-2-da5e6961a0b7

**Comment by K-Vinayak** [comment]
Amazing Article! 
I appreciate for recommending this crate. Thanks.

For the implementation, did you want a use case like this?

```rust
struct Complx(i32, i32);

gen_ops!(
    types Complx, Complx => Complx;
    /// Adds two complex numbers
    for + call |a: Complx, b: Complx| Complx(a.0+b.0 , a.1+b.1);
)

impl std::ops::Add for Complx {
    type Output = Complx;

    #[doc = r" Adds two complex numbers"]
    #[inline]
    fn add(self, other:Complx) -> Complx {
        //... call the closure here
    }
}
```
I was testing a little bit and saw that rust-analyzer doesn't always show the docs when hovered over the operator. It just shows default docs for the operator instead. I'll look into that once I add the feature to the core macros.

**Comment by CarlKCarlK** [comment]
That looks great. Thanks for working on this.

**Comment by K-Vinayak** [comment]
Hello Carl,

New version is published with the feature! Please confirm to close this issue.

Regards,
K Vinayak

**Comment by CarlKCarlK** [comment]
It's working. Thanks!
