### ISSUE TITLE
Guidance needed on using in 'no_std project 

### ISSUE THREAD

**Issue by CarlKCarlK** [K-Vinayak/gen_ops#2]
Greetings, I have a user request to make range-set-blaze no_std. Currently, when I use get_ops_ex [(code)](https://github.com/CarlKCarlK/range-set-blaze/blob/no_std/src/lib.rs), I'm seeing errors:

> failed to resolve: could not find `std` in the list of imported crates
> could not find `std` in the list of imported crates

related to `std::ops::$trait` in `_core_impl_bin` in `gen_ops/src/core_impl.rs`

I'm new to no_std. Any guidance would be appreciated.

Thanks!

Yours,
Carl

```
#[doc(hidden)]
#[macro_export]
macro_rules! _core_impl_bin {
    (($($gen:tt)*);
    types $lhs:ty, $rhs:ty => $out:ty;
    refs $lref:ident $rref:ident $($rev:ident)?;
    $(#[$attr:meta])*
    for [$trait:ident $method:ident] call $func:expr;
    $((where $($where1:tt)+))?
    $(where $($where:tt)+)?) => {
        impl $($gen)* ::std::ops::$trait<$crate::_refmut!($rref $rhs)> for $crate::_refmut!($lref $lhs)
        where $($($where)+ ,)? $($($where1)+)? {
            type Output = $out;
            $(#[$attr])*
            #[inline]
            fn $method(self, rhs: $crate::_refmut!($rref $rhs)) -> $out {
                $crate::_inner_func_call_bin!($($rev)? $lref self $rref rhs $func)
            }
        }
    };
}
```

**Comment by CarlKCarlK** [comment]
I found this workaround:

* manually expanded the macro
* switched ::std::ops to ::core::ops, for example, ::core::ops::BitAnd

It works, but I'm no longer using gen_ops_ex! and now my code is much harder to read.

**Comment by K-Vinayak** [comment]
Hello Carl,

Thanks for pointing this out! Due to some limitation during initial development I had to hard code `std::` prefix in the macros. I'll test and see if switching it to `core` now works. 

Since the crate is marked as `no_std` it's supposed to work with other `no_std` crates without any problems. I'll get back after some testing. 

Regards,
K Vinayak

**Comment by K-Vinayak** [comment]
Hello Carl,

I see that switching `std` to `core` works flawlessly. I'll release the the version soon with the fix

Regards,
K Vinayak

**Comment by K-Vinayak** [comment]
Hello Carl,

New version is up. It's fixed now. It should work with both `std` and `core`. I think we can close this issue 

Regards,
K Vinayak

**Comment by CarlKCarlK** [comment]
Thanks! Yes, close the issue.

**Comment by K-Vinayak** [comment]
Thanks for the confirmation. Closing the issue
